// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Clouds struct {
	All *int `json:"all,omitempty"`
}

type Coord struct {
	Lon *float64 `json:"lon,omitempty"`
	Lat *float64 `json:"lat,omitempty"`
}

type Main struct {
	Temp      *float64 `json:"temp,omitempty"`
	FeelsLike *float64 `json:"feelsLike,omitempty"`
	TempMin   *float64 `json:"tempMin,omitempty"`
	TempMax   *float64 `json:"tempMax,omitempty"`
	Pressure  *int     `json:"pressure,omitempty"`
	Humidity  *int     `json:"humidity,omitempty"`
	SeaLevel  *int     `json:"seaLevel,omitempty"`
	GrndLevel *int     `json:"grndLevel,omitempty"`
}

type Query struct {
}

type Rain struct {
	H *float64 `json:"h,omitempty"`
}

type Sys struct {
	Type    *int    `json:"type,omitempty"`
	ID      *int    `json:"id,omitempty"`
	Country *string `json:"country,omitempty"`
	Sunrise *int    `json:"sunrise,omitempty"`
	Sunset  *int    `json:"sunset,omitempty"`
}

type WeatherCondition struct {
	ID          *int    `json:"id,omitempty"`
	Main        *string `json:"main,omitempty"`
	Description *string `json:"description,omitempty"`
	Icon        *string `json:"icon,omitempty"`
}

type WeatherData struct {
	Coord               *Coord              `json:"coord,omitempty"`
	Weather             []*WeatherCondition `json:"weather,omitempty"`
	Base                *string             `json:"base,omitempty"`
	Main                *Main               `json:"main,omitempty"`
	Visibility          *int                `json:"visibility,omitempty"`
	Wind                *Wind               `json:"wind,omitempty"`
	Rain                *Rain               `json:"rain,omitempty"`
	Clouds              *Clouds             `json:"clouds,omitempty"`
	Dt                  *int                `json:"dt,omitempty"`
	Sys                 *Sys                `json:"sys,omitempty"`
	Timezone            *int                `json:"timezone,omitempty"`
	ID                  *int                `json:"id,omitempty"`
	Name                *string             `json:"name,omitempty"`
	Cod                 *int                `json:"cod,omitempty"`
	TemperateAssessment *string             `json:"temperateAssessment,omitempty"`
}

type Wind struct {
	Speed *float64 `json:"speed,omitempty"`
	Deg   *int     `json:"deg,omitempty"`
	Gust  *float64 `json:"gust,omitempty"`
}
